### PR TITLE
resize template adjust for 2023.2 for Moving with Alveo example

### PR DESCRIPTION
**Pull request by FredKellerman**
This makes the moving with Alveo example work with the 2023.2 tools and the existing Makefile.

### CODE REVIEW

**Comment by imrickysu** [comment]
@FredKellerman  Thanks for submitting this PR. We will verify and merge.

**Comment by imrickysu** [comment]
@AnusheelXilinx  could you review and test? Thanks.

**Comment by AnusheelXilinx** [comment]
I missed updating here, the changes worked. Thanks!

**Comment by allyzhou** [comment]
confirmed by Anusheel, and the same change will be applied to 2024.1. Thanks.

**Pull request merged**
