### PR TITLE
Update AI engine 01-aie_lenet_tutorial:  Add XRT related lib and header file search path and modify host header path of xrt

### PR DESCRIPTION
**Pull request by sven2314**

### CODE REVIEW

**Comment by SURUTHI1605** [comment]
This tutorial will work even without these changes.Because we replaced the XILINX_XRT with SDKTARGETSYSROOT variable from 2022 release.What's the point of adding it here? Please add a comment for these changes.

**Comment by sven2314** [comment]
As the SDKTARGETSYSROOT variable is exported. No need to add  XILINX_XRT variable. So close this PR.

**Comment by keryell** [comment]
Is there someone looking at the variable environment naming coding style? @stsoe 
`SDKTARGETSYSROOT` looks like alien to the project. Perhaps at least `SDK_TARGET_SYSROOT`?
But `SDK` seems pretty vague too. There are a lot of SDK in the world. :-)

**Comment by allyzhou** [comment]
> Is there someone looking at the variable environment naming coding style? @stsoe `SDKTARGETSYSROOT` looks like alien to the project. Perhaps at least `SDK_TARGET_SYSROOT`? But `SDK` seems pretty vague too. There are a lot of SDK in the world. :-)

@sven2314 @imrickysu  can either of you comment here? Thanks

**Pull request closed without merging**
