### PR TITLE
Adapt Tcl scripts to 2021.2 for KV260 platform creation tutorial

### PR DESCRIPTION
**Pull request by vmayoral**
Signed-off-by: Víctor Mayoral Vilches <v.mayoralv@gmail.com>

### CODE REVIEW

**Comment by imrickysu** [comment]
Hi @vmayoral , thanks for your contribution to the KV260 platform creation tutorial.

This tutorial was not upgraded to 2021.2 because Kria doesn't have a PetaLinux BSP for 2021.2. Though it should still work if we adapt the design to 2021.2 Vivado, use 2021.1 BSP generated sysroot, and generate the platform with 2021.2 Vitis, we don't get much additional features, and we still miss the Vitis-AI for 2021.2.

Generally when we upgrade tutorials, besides the Vivado script version checking, we also need to update the whole bd tcl because IP version may change and the default IP configuration may vary. 

If you have validated the whole process in 2021.2, it's good to know. We can add this note and add upgrade instructions to the readme document.

**Comment by vmayoral** [comment]
Works for me with this change with 2021.2.

**Comment by imrickysu** [comment]
Thanks @vmayoral for the confirmation. I'll add notes to the KV260 tutorial README.

**Comment by imrickysu** [comment]
This info is now added by PR #195

**Pull request closed without merging**
